name: Build tmux for macOS and Ubuntu

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install dependencies on macOS
        if: runner.os == 'macOS'
        run: |
          brew install automake autoconf libevent pkg-config ncurses utf8proc

      - name: Install dependencies on Ubuntu
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y automake autoconf build-essential libevent-dev ncurses-dev pkg-config libutf8proc-dev

      - name: Build tmux
        run: |
          sh autogen.sh
          ./configure --prefix=$HOME/tmux --enable-utf8proc
          make
          make install

      - name: Package binary
        run: |
          mkdir -p output
          cp $HOME/tmux/bin/tmux output/

  upload:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Download binaries from all jobs
        uses: actions/download-artifact@v4
        with:
          path: output

      - name: Create GitHub Release and Upload Artifacts
        uses: ncipollo/release-action@v1
        with:
          artifacts: output/*
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ github.run_number }}
          name: "tmux Build ${{ github.run_number }}"
          body: |
            Prebuilt tmux binaries for macOS and Ubuntu.
          draft: false
          prerelease: false

